import type { InsertAttraction } from "../shared/schema";

export const seedAttractions: InsertAttraction[] = [
  {
    name: "Grand Palace",
    location: "Bangkok, Thailand",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Grand_Palace.jpg",
    description: "Official residence of Thai monarchs featuring dazzling gold spires and ornate architecture.",
    visitorCount: "1.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Petra",
    location: "Ma'an, Jordan",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Petra.jpg",
    description: "Ancient city carved into rose-red sandstone cliffs, showcasing Nabataean architecture.",
    visitorCount: "1.1 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Table Mountain",
    location: "Cape Town, South Africa",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Table_Mountain.jpg",
    description: "Africa's iconic landmark offering breathtaking panoramic views of Cape Town.",
    visitorCount: "1.4 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Neuschwanstein Castle",
    location: "Schwangau, Germany",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Neuschwanstein.jpg",
    description: "Fairy-tale castle perched dramatically in the Bavarian Alps with white limestone walls.",
    visitorCount: "1.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Duomo",
    location: "Florence, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Florence_Cathedral.jpg",
    description: "Masterpiece of Italian Gothic with revolutionary dome and multicolored marble facade.",
    visitorCount: "1.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Machu Picchu",
    location: "Cusco Region, Peru",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Machu_Picchu.jpg",
    description: "Lost City of Incas hidden in Andes mountains, a mystical 15th century citadel.",
    visitorCount: "1.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Christ the Redeemer",
    location: "Rio de Janeiro, Brazil",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Christ_the_Redeemer.jpg",
    description: "Colossal Art Deco statue towering over Rio, a global icon of Brazil.",
    visitorCount: "1.8 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "The Louvre Abu Dhabi",
    location: "Abu Dhabi, UAE",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Louvre_Abu_Dhabi.jpg",
    description: "Modern museum with spectacular geometric dome and world-class art collections.",
    visitorCount: "2.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Dome of the Rock",
    location: "Jerusalem, Israel",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Dome_of_the_Rock.jpg",
    description: "Golden dome rising from Temple Mount since 691 AD, sacred to multiple faiths.",
    visitorCount: "2.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Duomo di Milano",
    location: "Milan, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Duomo_Milan.jpg",
    description: "World's largest Gothic cathedral covered in intricate spires and sculptures.",
    visitorCount: "2.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Edinburgh Castle",
    location: "Edinburgh, UK",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Edinburgh_Castle.jpg",
    description: "Fortress atop volcano dominating Edinburgh's skyline for over a thousand years.",
    visitorCount: "2.2 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Mont Saint-Michel",
    location: "Normandy, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Mont_Saint-Michel.jpg",
    description: "Medieval abbey crowning a rocky island rising dramatically from Normandy coast.",
    visitorCount: "2.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Chichen Itza",
    location: "Yucatán, Mexico",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Chichen_Itza.jpg",
    description: "Major Mayan site with El Castillo pyramid, sacred cenotes, and carvings.",
    visitorCount: "2.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Angkor Wat",
    location: "Siem Reap, Cambodia",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Angkor_Wat.jpg",
    description: "World's largest religious monument, stunning 12th century Khmer temple complex.",
    visitorCount: "2.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Alhambra",
    location: "Granada, Spain",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Alhambra.jpg",
    description: "Islamic fortress-palace with ornate carvings, graceful arches, geometric patterns.",
    visitorCount: "2.7 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Buckingham Palace",
    location: "London, UK",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Buckingham_Palace.jpg",
    description: "Official royal residence with neoclassical architecture and famous guard ceremony.",
    visitorCount: "2.7 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Tower of London",
    location: "London, UK",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Tower_of_London.jpg",
    description: "Historic fortress guarding Thames for a thousand years, housing Crown Jewels.",
    visitorCount: "2.9 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Reichstag Building",
    location: "Berlin, Germany",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Reichstag_Building.jpg",
    description: "Germany's parliament with stunning architecture and iconic dome with city views.",
    visitorCount: "3.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Temple of Heaven",
    location: "Beijing, China",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Temple_of_Heaven.jpg",
    description: "Sacred 15th century complex where emperors performed rituals for harvests.",
    visitorCount: "3.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Hagia Sophia",
    location: "Istanbul, Turkey",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Hagia_Sophia.jpg",
    description: "Byzantine masterpiece with revolutionary dome blending Christian and Islamic art.",
    visitorCount: "3.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Meiji Shrine",
    location: "Tokyo, Japan",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Meiji_Shrine.jpg",
    description: "Serene Shinto shrine in forest sanctuary offering peaceful respite from city.",
    visitorCount: "3.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Acropolis",
    location: "Athens, Greece",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Acropolis.jpg",
    description: "Home to Parthenon, humanity's greatest classical achievement from 2,500 years ago.",
    visitorCount: "3.1 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Musée d'Orsay",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Musee_d_Orsay.jpg",
    description: "Former train station showcasing Impressionist masterpieces by Monet, Van Gogh.",
    visitorCount: "3.7 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Schönbrunn Palace",
    location: "Vienna, Austria",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Schonbrunn_Palace.jpg",
    description: "Austria's grandest palace with opulent Rococo architecture and grand gardens.",
    visitorCount: "3.8 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Pompeii",
    location: "Naples, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Pompeii.jpg",
    description: "Roman city frozen in time by Vesuvius eruption, revealing ancient daily life.",
    visitorCount: "3.8 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Palace Museum",
    location: "Taipei, Taiwan",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Palace_Museum.jpg",
    description: "World's greatest Chinese imperial art collection spanning 8,000 years history.",
    visitorCount: "4.4 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Statue of Liberty",
    location: "New York City, USA",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Statue_of_Liberty.jpg",
    description: "Colossal copper statue symbolizing freedom, welcoming millions over a century.",
    visitorCount: "4.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Blue Mosque",
    location: "Istanbul, Turkey",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Blue_Mosque.jpg",
    description: "Ottoman mosque with six minarets and thousands of hand-painted blue tiles.",
    visitorCount: "4.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Sagrada Familia",
    location: "Barcelona, Spain",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Sagrada_Familia.jpg",
    description: "Gaudí's unfinished basilica with soaring towers and stained glass masterpiece.",
    visitorCount: "4.7 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Hermitage Museum",
    location: "St. Petersburg, Russia",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Hermitage_Museum.jpg",
    description: "Former Winter Palace housing world's greatest collection with 3 million works.",
    visitorCount: "4.9 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "St. Mark's Basilica",
    location: "Venice, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/St_Marks_Basilica.jpg",
    description: "Byzantine masterpiece with five domes, golden mosaics, and shimmering marble.",
    visitorCount: "5.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Cologne Cathedral",
    location: "Cologne, Germany",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Cologne_Cathedral.jpg",
    description: "Gothic cathedral with twin 157-meter spires built over 600 years to complete.",
    visitorCount: "6.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Eiffel Tower",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Eiffel_Tower.jpg",
    description: "Iconic iron tower piercing Parisian sky at 330 meters, built for 1889 Fair.",
    visitorCount: "6.1 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Burj Khalifa",
    location: "Dubai, UAE",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Burj_Khalifa.jpg",
    description: "World's tallest building at 829.8 meters with incredible observation views.",
    visitorCount: "6.2 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "British Museum",
    location: "London, UK",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/British_Museum.jpg",
    description: "World-class museum with Rosetta Stone, Egyptian mummies, and free admission.",
    visitorCount: "6.2 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Vatican Museums",
    location: "Vatican City",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Vatican_Museums.jpg",
    description: "Housing Michelangelo's Sistine Chapel ceiling and Renaissance masterpieces.",
    visitorCount: "6.9 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Taj Mahal",
    location: "Agra, India",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Taj_Mahal.jpg",
    description: "Ivory-white marble mausoleum with perfect symmetry, world's most beautiful.",
    visitorCount: "7.4 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Colosseum",
    location: "Rome, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Colosseum.jpg",
    description: "Ancient Roman amphitheater from 80 AD, pinnacle of Roman engineering power.",
    visitorCount: "7.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Lincoln Memorial",
    location: "Washington, D.C., USA",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Lincoln_Memorial-1.jpg",
    description: "Tribute to Lincoln where MLK delivered his I Have a Dream speech.",
    visitorCount: "7.9 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Palace of Versailles",
    location: "Versailles, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Palace_of_Versailles.jpg",
    description: "Symbol of monarchy with Hall of Mirrors, lavish apartments, grand gardens.",
    visitorCount: "8.1 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Sydney Opera House",
    location: "Sydney, Australia",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Sydney_Opera_House.jpg",
    description: "Iconic sail-shaped shells rising majestically from Sydney Harbour waterfront.",
    visitorCount: "8.2 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Louvre Museum",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Louvre_Museum.jpg",
    description: "World's most visited museum with Mona Lisa and iconic glass pyramid entrance.",
    visitorCount: "9.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Hollywood Walk of Fame",
    location: "Los Angeles, USA",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Hollywood_Walk_of_Fame.jpg",
    description: "Over 2,700 brass stars honoring entertainment legends along Hollywood Boulevard.",
    visitorCount: "10 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Great Wall of China",
    location: "Badaling, China",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Great_Wall_of_China.jpg",
    description: "Engineering marvel snaking across mountains for thousands of kilometers.",
    visitorCount: "10 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "St. Peter's Basilica",
    location: "Rome, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/St_Peters_Basilica.jpg",
    description: "World's largest church and Renaissance masterpiece with Michelangelo's dome.",
    visitorCount: "11 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Sacré-Cœur Basilica",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Sacre-Coeur-Basilica.jpg",
    description: "White basilica on Montmartre hill with sweeping panoramic views of Paris.",
    visitorCount: "11 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Notre-Dame Cathedral",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Notre-Dame_Cathedral.jpg",
    description: "Gothic masterpiece famous for flying buttresses, rose windows, stonework.",
    visitorCount: "13.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Forbidden City",
    location: "Beijing, China",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Forbidden_City.jpg",
    description: "World's largest palace complex with 1,000 golden-roofed buildings inside.",
    visitorCount: "17.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Niagara Falls",
    location: "Ontario, Canada / NY, USA",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Niagara_Falls.jpg",
    description: "Natural wonder with massive cascading waterfalls creating rainbows in mist.",
    visitorCount: "22.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Senso-ji Temple",
    location: "Tokyo, Japan",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Senso-ji-Temple.jpg",
    description: "Tokyo's oldest temple in Asakusa with giant red lantern and vibrant energy.",
    visitorCount: "30.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
];
