import type { InsertAttraction } from "../shared/schema";

export const seedAttractions: InsertAttraction[] = [
  {
    name: "Grand Palace",
    location: "Bangkok, Thailand",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Grand_Palace.jpg",
    description: "Thai kings have lived here for ages, and the place feels packed with history. Gold spires, colorful roofs, and intricate artwork catch your eye everywhere.",
    visitorCount: "1.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Petra",
    location: "Ma'an, Jordan",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Petra.jpg",
    description: "This legendary spot in Jordan is carved straight into pinkish rock. The Treasury and the Monastery stand out as you weave through narrow canyons and winding paths.",
    visitorCount: "1.1 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Table Mountain",
    location: "Cape Town, South Africa",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Table_Mountain.jpg",
    description: "Table Mountain dominates the skyline. Locals and visitors alike flock to the cable car for what might be the best views in South Africa.",
    visitorCount: "1.4 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Neuschwanstein Castle",
    location: "Schwangau, Germany",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Neuschwanstein.jpg",
    description: "Perches on a rugged hill in southern Germany, looking like it leapt out of a fairy tale. Tall towers and sweeping views of the Alps make it easy to see why crowds flock here.",
    visitorCount: "1.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Duomo",
    location: "Florence, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Florence_Cathedral.jpg",
    description: "The Cathedral of Santa Maria del Fiore, smack in the city center. Inside, stained glass and a massive painted dome catch your eye. The marble outside—green, pink, and white—really pops in the sunlight.",
    visitorCount: "1.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Machu Picchu",
    location: "Cusco Region, Peru",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Machu_Picchu.jpg",
    description: "Known as the Lost City of the Incas, it dates back to the 1400s and stayed hidden for centuries. Ancient stone walls, temples, and terraces surrounded by steep, green cliffs.",
    visitorCount: "1.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Christ the Redeemer",
    location: "Rio de Janeiro, Brazil",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Christ_the_Redeemer.jpg",
    description: "Towers over the city from Corcovado Mountain. The Art Deco statue is an absolute icon and made the list of the New 7 Wonders of the World.",
    visitorCount: "1.8 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "The Louvre Abu Dhabi",
    location: "Abu Dhabi, UAE",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Louvre_Abu_Dhabi.jpg",
    description: "Stands out with its futuristic dome and cool light patterns inside. The museum sits right on the water with art from all over—ancient statues, modern paintings, and everything in between.",
    visitorCount: "2.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Dome of the Rock",
    location: "Jerusalem, Israel",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Dome_of_the_Rock.jpg",
    description: "That golden dome shines from across the city, perched on the Temple Mount. Built in the late 7th century, it holds deep meaning for Muslims, Jews, and Christians alike.",
    visitorCount: "2.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Duomo di Milano",
    location: "Milan, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Duomo_Milan.jpg",
    description: "This enormous cathedral sits right in the city center, covered in Gothic spires and statues. You can climb up to the rooftop for a panoramic view.",
    visitorCount: "2.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Edinburgh Castle",
    location: "Edinburgh, UK",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Edinburgh_Castle.jpg",
    description: "Sits high above the city, impossible to miss. Inside, you'll wander through old stone corridors and rooms filled with royal treasures.",
    visitorCount: "2.2 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Mont Saint-Michel",
    location: "Normandy, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Mont_Saint-Michel.jpg",
    description: "Rises out of the Normandy bay, a tiny island with a huge story. The medieval abbey on top draws the eye from miles away. A UNESCO World Heritage Site.",
    visitorCount: "2.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Chichen Itza",
    location: "Yucatán, Mexico",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Chichen_Itza.jpg",
    description: "One of Mexico's busiest sites with legendary Mayan ruins. El Castillo, the iconic pyramid, ancient temples, stone carvings, and old ball courts.",
    visitorCount: "2.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Angkor Wat",
    location: "Siem Reap, Cambodia",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Angkor_Wat.jpg",
    description: "One of the largest religious monuments on the planet. The blend of mossy stone temples and lush scenery pulls in everyone from photographers to history buffs.",
    visitorCount: "2.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Alhambra",
    location: "Granada, Spain",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Alhambra.jpg",
    description: "Part palace, part fortress, part garden. Halls covered in detailed carvings, graceful arches, and colorful tiles. Its Islamic art and architecture are legendary.",
    visitorCount: "2.7 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Buckingham Palace",
    location: "London, UK",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Buckingham_Palace.jpg",
    description: "The official home of the British monarch. The gates, the changing of the guard, and the palace itself. In summer, you can tour some rooms and stroll through the gardens.",
    visitorCount: "2.7 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Tower of London",
    location: "London, UK",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Tower_of_London.jpg",
    description: "This fortress has watched over the Thames for nearly a thousand years. Famous Tower ravens, guards in red, and the dazzling Crown Jewels.",
    visitorCount: "2.9 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Reichstag Building",
    location: "Berlin, Germany",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Reichstag_Building.jpg",
    description: "Sits right in the heart of Berlin. German parliament meets here. The glass dome offers views over Berlin, spotting landmarks all around.",
    visitorCount: "3.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Temple of Heaven",
    location: "Beijing, China",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Temple_of_Heaven.jpg",
    description: "A massive park with ancient temples and gardens, dating back to the 15th century. The Hall of Prayer for Good Harvests stands out with its round blue roof.",
    visitorCount: "3.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Hagia Sophia",
    location: "Istanbul, Turkey",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Hagia_Sophia.jpg",
    description: "Started life as a Greek Orthodox cathedral in 537 AD. Its revolutionary massive dome was an architectural game-changer. Christian mosaics alongside Islamic calligraphy.",
    visitorCount: "3.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Meiji Shrine",
    location: "Tokyo, Japan",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Meiji_Shrine.jpg",
    description: "Surprisingly quiet for being in the heart of Tokyo. The giant wooden torii gate marks the entrance, and you'll walk shaded paths under tall trees.",
    visitorCount: "3.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Acropolis",
    location: "Athens, Greece",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Acropolis.jpg",
    description: "The symbol of classical Greece and the birthplace of democracy. The Parthenon has stood for nearly 2,500 years, living proof of ancient architectural brilliance.",
    visitorCount: "3.1 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Musée d'Orsay",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Musee_d_Orsay.jpg",
    description: "Inside an old train station with huge clocks and soaring glass ceilings. Works from Monet, Van Gogh, Degas, and more covering the 1800s to early 1900s.",
    visitorCount: "3.7 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Schönbrunn Palace",
    location: "Vienna, Austria",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Schonbrunn_Palace.jpg",
    description: "Austria's top tourist spot. Grand rooms once used by emperors. Golden halls, manicured gardens, and classic art everywhere. A UNESCO World Heritage Site.",
    visitorCount: "3.8 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Pompeii",
    location: "Naples, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Pompeii.jpg",
    description: "The ancient Roman city buried by a volcanic eruption in 79 AD. Houses, streets, and mosaics almost untouched, giving a glimpse of life centuries ago.",
    visitorCount: "3.8 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Palace Museum",
    location: "Taipei, Taiwan",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Palace_Museum.jpg",
    description: "Famous for its massive collection of ancient Chinese art and treasures. Paintings, ceramics, jade, and rare books covering over 8,000 years of history.",
    visitorCount: "4.4 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Statue of Liberty",
    location: "New York City, USA",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Statue_of_Liberty.jpg",
    description: "Standing tall on Liberty Island. A symbol of freedom and a welcome to newcomers. The statue's been greeting visitors for over a century.",
    visitorCount: "4.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Blue Mosque",
    location: "Istanbul, Turkey",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Blue_Mosque.jpg",
    description: "Officially the Sultan Ahmed Mosque, finished in the early 1600s. Six tall minarets and thousands of blue tiles inside give the mosque its nickname.",
    visitorCount: "4.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Sagrada Familia",
    location: "Barcelona, Spain",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Sagrada_Familia.jpg",
    description: "Antoni Gaudí designed this basilica—there's nothing else quite like it. Stained glass windows throwing color everywhere. Still not finished, people keep coming.",
    visitorCount: "4.7 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Hermitage Museum",
    location: "St. Petersburg, Russia",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Hermitage_Museum.jpg",
    description: "One of the world's biggest art museums. Paintings, sculptures, and treasures from all over. The Winter Palace—where Russian emperors used to live.",
    visitorCount: "4.9 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "St. Mark's Basilica",
    location: "Venice, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/St_Marks_Basilica.jpg",
    description: "Rises above St. Mark's Square. Famous for its domes, golden mosaics, and crazy level of detail. Light shining through stained glass makes the artwork glow.",
    visitorCount: "5.5 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Cologne Cathedral",
    location: "Cologne, Germany",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Cologne_Cathedral.jpg",
    description: "Giant Gothic cathedral with iconic twin spires soaring 157 meters high. Construction started in 1248 and wasn't completed until 1880. Miraculously survived WWII bombing.",
    visitorCount: "6.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Eiffel Tower",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Eiffel_Tower.jpg",
    description: "The wrought-iron lattice tower pierces the Parisian sky at 330 meters. Built as the entrance arch for the 1889 World's Fair, now a beloved symbol of French ingenuity.",
    visitorCount: "6.1 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Burj Khalifa",
    location: "Dubai, UAE",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Burj_Khalifa.jpg",
    description: "The tallest building on earth at 829.8 meters. The observation deck offers incredible city views. The Dubai Fountain's wild water shows nearby.",
    visitorCount: "6.2 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "British Museum",
    location: "London, UK",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/British_Museum.jpg",
    description: "Objects from ancient Egypt, Greece, Rome, and all sorts of cultures. The Rosetta Stone is here. Entry is free. Opened in 1759 and still one of the busiest places in the UK.",
    visitorCount: "6.2 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Vatican Museums",
    location: "Vatican City",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Vatican_Museums.jpg",
    description: "Art by Raphael, Michelangelo, and other legends. The Sistine Chapel with its famous ceiling. Halls filled with sculptures, paintings, and old maps.",
    visitorCount: "6.9 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Taj Mahal",
    location: "Agra, India",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Taj_Mahal.jpg",
    description: "An epic love poem crafted in ivory-white marble. Commissioned by Shah Jahan as a mausoleum for his beloved wife. Perfect symmetry and incredibly intricate inlay work.",
    visitorCount: "7.4 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Colosseum",
    location: "Rome, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Colosseum.jpg",
    description: "Massive stone amphitheater completed in 80 AD. Could hold 50,000 to 80,000 spectators for gladiatorial contests. An imposing example of Roman engineering.",
    visitorCount: "7.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Lincoln Memorial",
    location: "Washington, D.C., USA",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Lincoln_Memorial-1.jpg",
    description: "A commanding tribute to Abraham Lincoln. White marble structure in Greek Doric temple style with a large seated statue. Site of MLK's 'I Have a Dream' speech.",
    visitorCount: "7.9 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Palace of Versailles",
    location: "Versailles, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Palace_of_Versailles.jpg",
    description: "The ultimate symbol of the absolute monarchy. The dazzling Hall of Mirrors, lavish apartments, and meticulously landscaped gardens designed by André Le Nôtre.",
    visitorCount: "8.1 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Sydney Opera House",
    location: "Sydney, Australia",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Sydney_Opera_House.jpg",
    description: "Those white, sail-shaped roofs are iconic. Right by the water with harbor views. Several performance halls inside for concerts, plays, and ballet.",
    visitorCount: "8.2 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Louvre Museum",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Louvre_Museum.jpg",
    description: "The glass pyramid out front and the massive art collection inside. Home to the Mona Lisa. Ancient statues, Egyptian mummies, and famous paintings fill the halls.",
    visitorCount: "9.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Hollywood Walk of Fame",
    location: "Los Angeles, USA",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Hollywood_Walk_of_Fame.jpg",
    description: "Over 2,700 stars set into the sidewalk honoring actors, musicians, and directors. The pink and gold stars stretch for more than a mile along Hollywood Boulevard.",
    visitorCount: "10 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Great Wall of China",
    location: "Badaling, China",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Great_Wall_of_China.jpg",
    description: "The most popular section for tourists. Stone walls and towers snake across the hills, showing off the wall's age and scale. Mountain views are awesome.",
    visitorCount: "10 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "St. Peter's Basilica",
    location: "Rome, Italy",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/St_Peters_Basilica.jpg",
    description: "The largest church in the world and a masterpiece of Renaissance architecture. Home to Michelangelo's Pietà and Bernini's bronze baldachin.",
    visitorCount: "11 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Sacré-Cœur Basilica",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Sacre-Coeur-Basilica.jpg",
    description: "Sits on top of Montmartre hill giving some of the best city views in Paris. The white stone pops against the sky. Street artists and cafes everywhere.",
    visitorCount: "11 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Notre-Dame Cathedral",
    location: "Paris, France",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Notre-Dame_Cathedral.jpg",
    description: "Paris's most visited spot right on the River Seine. Huge towers, stained glass, and detailed carvings. Gothic architecture that grabs your attention.",
    visitorCount: "13.6 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Forbidden City",
    location: "Beijing, China",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Forbidden_City.jpg",
    description: "Served as the imperial palace for almost 500 years. A vast labyrinth of nearly 1,000 buildings with golden-tiled roofs, red walls, and intricate courtyards.",
    visitorCount: "17.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Niagara Falls",
    location: "Ontario, Canada / NY, USA",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Niagara_Falls.jpg",
    description: "Right on the border between Canada and the United States. Massive waterfalls you can ride a boat close to. The mist and rainbows are as cool as everyone says.",
    visitorCount: "22.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
  {
    name: "Senso-ji Temple",
    location: "Tokyo, Japan",
    imageUrl: "https://www.touropia.com/gfx/b/2025/05/Senso-ji-Temple.jpg",
    description: "Tokyo's oldest temple in Asakusa. The giant red lantern at the Thunder Gate is classic Tokyo. Stalls with souvenirs and snacks—the whole scene feels alive.",
    visitorCount: "30.0 million",
    eloScore: 1200,
    matchesPlayed: 0,
  },
];
